### ISSUE TITLE
[BUG] AutoSprint is not Multi-Directional

### ISSUE THREAD

**Issue by pastimee** [AresClient/ares#34]
**What version is this applicable?**
Forge

**Describe the bug**
The AutoSprint module does not allow sprinting in all directions, only in the forward's and backward's direction, strafing (moving left or right) will not give you the sprint modifier.

**To Reproduce**
1. Toggle AutoSprint.
2. Walk from side to side, you will see your speed is 15 km/h (the walking speed), where it should be 20 km/h (the sprinting speed)

**Screenshots**
None.

**Additional context**
Using Ares 2.8.

**Comment by ghost** [comment]
You would have to send rotation packets to be able to sprint sideways or backwards, which would trigger the anticheat on many servers due to the very quick snapping to a very different position. You cant sprint any direction normally, and auto sprint just sets that you are sprinting (cant sprint in every direction, only forward).

**Comment by pastimee** [comment]
The description says that it enables sprinting in all directions, also Future (sprint mode: rage) is able to do this on pretty much any anarchy server.

**Comment by Tigermouthbear** [comment]
fixed in 1.17 branch, will be merged into master after 1.17 is done
